var mongoose = require('mongoose')

var sera = mongoose.Schema({
    isRead: Boolean,
    subject: String,
    from: String,
    receivedDateTime: Date,
    sentDateTime: Date
});
//2019-03-01T:00:12:00Z

module.exports = mongoose.model("SERA", sera)
//module.exports.reportSchema = reportSchema;
// mongoose.model("Report", reportSchema)





// working copy
// var mongoose = require('mongoose')

// var reportSchema = mongoose.Schema({
//     // id generated by mongo
//     _id: mongoose.Schema.Types.ObjectId,
//     firstname: String,
//     lastname: String
// });

// module.exports = mongoose.model("Report", reportSchema)
//module.exports.reportSchema = reportSchema;
// mongoose.model("Report", reportSchema)